// NYSECompanies.js

const topNYSECompanies = [
    { symbol: "JPM", name: "JPMorgan Chase & Co." },
    { symbol: "V", name: "Visa Inc." },
    { symbol: "JNJ", name: "Johnson & Johnson" },
    { symbol: "WMT", name: "Walmart Inc." },
    { symbol: "PG", name: "Procter & Gamble Company" },
    { symbol: "XOM", name: "Exxon Mobil Corporation" },
    { symbol: "BAC", name: "Bank of America Corporation" },
    { symbol: "MA", name: "Mastercard Incorporated" },
    { symbol: "DIS", name: "The Walt Disney Company" },
    { symbol: "CVX", name: "Chevron Corporation" },
    { symbol: "KO", name: "The Coca-Cola Company" },
    { symbol: "MRK", name: "Merck & Co., Inc." },
    { symbol: "PFE", name: "Pfizer Inc." },
    { symbol: "VZ", name: "Verizon Communications Inc." },
    { symbol: "ABBV", name: "AbbVie Inc." },
    { symbol: "PEP", name: "PepsiCo, Inc." },
    { symbol: "T", name: "AT&T Inc." },
    { symbol: "NKE", name: "NIKE, Inc." },
    { symbol: "UNH", name: "UnitedHealth Group Incorporated" },
    { symbol: "CRM", name: "Salesforce, Inc." },
    { symbol: "ORCL", name: "Oracle Corporation" },
    { symbol: "HD", name: "The Home Depot, Inc." },
    { symbol: "MCD", name: "McDonald's Corporation" },
    { symbol: "ABT", name: "Abbott Laboratories" },
    { symbol: "TMO", name: "Thermo Fisher Scientific Inc." },
    { symbol: "ACN", name: "Accenture plc" },
    { symbol: "IBM", name: "International Business Machines Corporation" },
    { symbol: "LLY", name: "Eli Lilly and Company" },
    { symbol: "BA", name: "The Boeing Company" },
    { symbol: "CAT", name: "Caterpillar Inc." },
    { symbol: "GE", name: "General Electric Company" },
    { symbol: "MMM", name: "3M Company" },
    { symbol: "HON", name: "Honeywell International Inc." },
    { symbol: "AXP", name: "American Express Company" },
    { symbol: "UNP", name: "Union Pacific Corporation" },
    { symbol: "RTX", name: "Raytheon Technologies Corporation" },
    { symbol: "NEE", name: "NextEra Energy, Inc." },
    { symbol: "LMT", name: "Lockheed Martin Corporation" },
    { symbol: "SCHW", name: "The Charles Schwab Corporation" },
    { symbol: "CVS", name: "CVS Health Corporation" },
    { symbol: "LOW", name: "Lowe's Companies, Inc." },
    { symbol: "BMY", name: "Bristol-Myers Squibb Company" },
    { symbol: "AMT", name: "American Tower Corporation" },
    { symbol: "BLK", name: "BlackRock, Inc." },
    { symbol: "DHR", name: "Danaher Corporation" },
    { symbol: "DE", name: "Deere & Company" },
    { symbol: "ADP", name: "Automatic Data Processing, Inc." },
    { symbol: "TJX", name: "The TJX Companies, Inc." },
    { symbol: "SPGI", name: "S&P Global Inc." },
    { symbol: "GS", name: "The Goldman Sachs Group, Inc." },
    { symbol: "MS", name: "Morgan Stanley" },
    { symbol: "MDT", name: "Medtronic plc" },
    { symbol: "USB", name: "U.S. Bancorp" },
    { symbol: "BDX", name: "Becton, Dickinson and Company" },
    { symbol: "MMC", name: "Marsh & McLennan Companies, Inc." },
    { symbol: "DUK", name: "Duke Energy Corporation" },
    { symbol: "ITW", name: "Illinois Tool Works Inc." },
    { symbol: "CI", name: "Cigna Corporation" },
    { symbol: "MET", name: "MetLife, Inc." },
    { symbol: "COST", name: "Costco Wholesale Corporation" },
    { symbol: "CCI", name: "Crown Castle Inc." },
    { symbol: "COP", name: "ConocoPhillips" },
    { symbol: "PLD", name: "Prologis, Inc." },
    { symbol: "UPS", name: "United Parcel Service, Inc." },
    { symbol: "EMR", name: "Emerson Electric Co." },
    { symbol: "AON", name: "Aon plc" },
    { symbol: "TRV", name: "The Travelers Companies, Inc." },
    { symbol: "PNC", name: "The PNC Financial Services Group, Inc." },
    { symbol: "DG", name: "Dollar General Corporation" },
    { symbol: "PSA", name: "Public Storage" },
    { symbol: "BK", name: "The Bank of New York Mellon Corporation" },
    { symbol: "NOC", name: "Northrop Grumman Corporation" },
    { symbol: "AEP", name: "American Electric Power Company, Inc." },
    { symbol: "APD", name: "Air Products and Chemicals, Inc." },
    { symbol: "SO", name: "The Southern Company" },
    { symbol: "WBA", name: "Walgreens Boots Alliance, Inc." },
    { symbol: "ANTM", name: "Anthem, Inc." },
    { symbol: "LIN", name: "Linde plc" },
    { symbol: "BKNG", name: "Booking Holdings Inc." },
    { symbol: "FDX", name: "FedEx Corporation" },
    { symbol: "ECL", name: "Ecolab Inc." },
    { symbol: "STZ", name: "Constellation Brands, Inc." },
    { symbol: "BSX", name: "Boston Scientific Corporation" },
    { symbol: "D", name: "Dominion Energy, Inc." },
    { symbol: "FIS", name: "Fidelity National Information Services, Inc." },
    { symbol: "GD", name: "General Dynamics Corporation" },
    { symbol: "KMB", name: "Kimberly-Clark Corporation" },
    { symbol: "WM", name: "Waste Management, Inc." },
    { symbol: "MPC", name: "Marathon Petroleum Corporation" },
    { symbol: "OXY", name: "Occidental Petroleum Corporation" },
    { symbol: "SLB", name: "Schlumberger Limited" },
    { symbol: "SYY", name: "Sysco Corporation" },
    { symbol: "AMGN", name: "Amgen Inc." },
    { symbol: "SYK", name: "Stryker Corporation" },
    { symbol: "AAPL", name: "Apple" },
    { symbol: "NVDA", name: "NVIDIA Corporation" },
    { symbol: "ADBE", name: "Adobe Inc." },
    { symbol: "INTC", name: "Intel Corporation" },
    { symbol: "MSFT", name: "Microsoft Corporation" },
    { symbol: "GOOGL", name: "Alphabet Inc. (Google)" },
    { symbol: "AMZN", name: "Amazon.com, Inc." },
    { symbol: "META", name: "Meta Platforms, Inc." },
    { symbol: "TSLA", name: "Tesla, Inc." },
    { symbol: "NFLX", name: "Netflix, Inc." },
    { symbol: "PYPL", name: "PayPal Holdings, Inc." },
    { symbol: "CSCO", name: "Cisco Systems, Inc." },
    { symbol: "ADSK", name: "Autodesk, Inc." },
    { symbol: "INTU", name: "Intuit Inc." },
    { symbol: "QCOM", name: "Qualcomm Incorporated" },
    { symbol: "ASML", name: "ASML Holding N.V." },
    { symbol: "AMD", name: "Advanced Micro Devices, Inc." },
    { symbol: "TXN", name: "Texas Instruments Incorporated" },
    { symbol: "MU", name: "Micron Technology, Inc." },
    { symbol: "AVGO", name: "Broadcom Inc." },
    { symbol: "LRCX", name: "Lam Research Corporation" },
      { symbol: "ZM", name: "Zoom Video Communications, Inc." },
  { symbol: "CRWD", name: "CrowdStrike Holdings, Inc." },
  { symbol: "OKTA", name: "Okta, Inc." },
  { symbol: "HUBS", name: "HubSpot, Inc." },
  { symbol: "TWLO", name: "Twilio Inc." },
  { symbol: "WDAY", name: "Workday, Inc." },
  { symbol: "SHOP", name: "Shopify Inc." },
  { symbol: "SQ", name: "Square Inc." },
  { symbol: "ROKU", name: "Roku, Inc." },
  { symbol: "LYFT", name: "Lyft, Inc." },
  { symbol: "COIN", name: "Coinbase Global, Inc." },
  { symbol: "ETSY", name: "Etsy, Inc." },
  { symbol: "UPST", name: "Upstart Holdings, Inc." },
  { symbol: "TWTR", name: "Twitter, Inc." },
  { symbol: "SNAP", name: "Snap Inc." },
  { symbol: "UBER", name: "Uber Technologies, Inc." },
  { symbol: "SNOW", name: "Snowflake Inc." },
  { symbol: "DOCU", name: "DocuSign, Inc." },
  { symbol: "TEAM", name: "Atlassian Corporation Plc" },
  ];
  
  export default topNYSECompanies;
  