// NYSECompanies.js

const topNYSECompanies = [
  { symbol: "AAPL", name: "Apple" },
  { symbol: "ABT", name: "Abbott Laboratories" },
  { symbol: "ABBV", name: "AbbVie Inc." },
  { symbol: "ACN", name: "Accenture plc" },
  { symbol: "ADBE", name: "Adobe Inc." },
  { symbol: "ADP", name: "Automatic Data Processing, Inc." },
  { symbol: "AMD", name: "Advanced Micro Devices, Inc." },
  { symbol: "AMGN", name: "Amgen Inc." },
  { symbol: "AMT", name: "American Tower Corporation" },
  { symbol: "AEP", name: "American Electric Power Company, Inc." },
  { symbol: "ANTM", name: "Anthem, Inc." },
  { symbol: "APD", name: "Air Products and Chemicals, Inc." },
  { symbol: "ASML", name: "ASML Holding N.V." },
  { symbol: "ATVI", name: "Activision Blizzard, Inc." },
  { symbol: "AVGO", name: "Broadcom Inc." },
  { symbol: "BA", name: "The Boeing Company" },
  { symbol: "BAC", name: "Bank of America Corporation" },
  { symbol: "BMY", name: "Bristol-Myers Squibb Company" },
  { symbol: "BLK", name: "BlackRock, Inc." },
  { symbol: "BDX", name: "Becton, Dickinson and Company" },
  { symbol: "C", name: "Citigroup Inc." },
  { symbol: "CAH", name: "Cardinal Health, Inc." },
  { symbol: "CAT", name: "Caterpillar Inc." },
  { symbol: "CB", name: "Chubb Limited" },
  { symbol: "CCL", name: "Carnival Corporation" },
  { symbol: "CDW", name: "CDW Corporation" },
  { symbol: "CE", name: "Celanese Corporation" },
  { symbol: "CERN", name: "Cerner Corporation" },
  { symbol: "CF", name: "CF Industries Holdings, Inc." },
  { symbol: "CHTR", name: "Charter Communications, Inc." },
  { symbol: "CI", name: "Cigna Corporation" },
  { symbol: "CL", name: "Colgate-Palmolive Company" },
  { symbol: "CLX", name: "Clorox Company" },
  { symbol: "CMA", name: "Comerica Incorporated" },
  { symbol: "CMCSA", name: "Comcast Corporation" },
  { symbol: "CMD", name: "Cantel Medical Corp." },
  { symbol: "CMI", name: "Cummins Inc." },
  { symbol: "CMS", name: "CMS Energy Corporation" },
  { symbol: "CNC", name: "Centene Corporation" },
  { symbol: "CNP", name: "CenterPoint Energy, Inc." },
  { symbol: "COF", name: "Capital One Financial Corporation" },
  { symbol: "COG", name: "Cabot Oil & Gas Corporation" },
  { symbol: "COL", name: "Rockwell Collins, Inc." },
  { symbol: "COM", name: "COMMVault Systems, Inc." },
  { symbol: "COP", name: "ConocoPhillips" },
  { symbol: "COST", name: "Costco Wholesale Corporation" },
  { symbol: "CPRT", name: "Copart, Inc." },
  { symbol: "CRM", name: "Salesforce, Inc." },
  { symbol: "CSCO", name: "Cisco Systems, Inc." },
  { symbol: "CSX", name: "CSX Corporation" },
  { symbol: "CTAS", name: "Cintas Corporation" },
  { symbol: "CTSH", name: "Cognizant Technology Solutions Corporation" },
  { symbol: "CTXS", name: "Citrix Systems, Inc." },
  { symbol: "CVS", name: "CVS Health Corporation" },
  { symbol: "CVX", name: "Chevron Corporation" },
  { symbol: "D", name: "Dominion Energy, Inc." },
  { symbol: "DAL", name: "Delta Air Lines, Inc." },
  { symbol: "DD", name: "DuPont de Nemours, Inc." },
  { symbol: "DE", name: "Deere & Company" },
  { symbol: "DHR", name: "Danaher Corporation" },
  { symbol: "DIS", name: "The Walt Disney Company" },
  { symbol: "DOV", name: "Dover Corporation" },
  { symbol: "DOW", name: "Dow, Inc." },
  { symbol: "DTE", name: "DTE Energy Company" },
  { symbol: "DUK", name: "Duke Energy Corporation" },
  { symbol: "DXC", name: "DXC Technology Company" },
  { symbol: "ECL", name: "Ecolab Inc." },
  { symbol: "ED", name: "Consolidated Edison, Inc." },
  { symbol: "EIX", name: "Edison International" },
  { symbol: "EL", name: "Estée Lauder Companies Inc." },
  { symbol: "EMN", name: "Eastman Chemical Company" },
  { symbol: "EMR", name: "Emerson Electric Co." },
  { symbol: "ENPH", name: "Enphase Energy, Inc." },
  { symbol: "EOG", name: "EOG Resources, Inc." },
  { symbol: "EPAM", name: "EPAM Systems, Inc." },
  { symbol: "EQIX", name: "Equinix, Inc." },
  { symbol: "EQR", name: "Equity Residential" },
  { symbol: "ES", name: "Eversource Energy" },
  { symbol: "ETN", name: "Eaton Corporation plc" },
  { symbol: "ETR", name: "Entergy Corporation" },
  { symbol: "EVRG", name: "Evergy, Inc." },
  { symbol: "EW", name: "Edwards Lifesciences Corporation" },
  { symbol: "EXC", name: "Exelon Corporation" },
  { symbol: "EXPD", name: "Expeditors International of Washington, Inc." },
  { symbol: "EXPE", name: "Expedia Group, Inc." },
  { symbol: "F", name: "Ford Motor Company" },
  { symbol: "FIS", name: "Fidelity National Information Services, Inc." },
  { symbol: "FISV", name: "FISV Inc." },
  { symbol: "FL", name: "Foot Locker, Inc." },
  { symbol: "FMC", name: "FMC Corporation" },
  { symbol: "FOXA", name: "Fox Corporation" },
  { symbol: "FOXB", name: "Fox Corporation" },
  { symbol: "FORD", name: "Ford Motor Company" },
  { symbol: "FR", name: "First Industrial Realty Trust, Inc." },
  { symbol: "FRT", name: "Federal Realty Investment Trust" },
  { symbol: "FTI", name: "FMC Technologies, Inc." },
  { symbol: "FTNT", name: "Fortinet, Inc." },
  { symbol: "GILD", name: "Gilead Sciences, Inc." },
  { symbol: "GIS", name: "General Mills, Inc." },
  { symbol: "GL", name: "Globe Life Inc." },
  { symbol: "GLW", name: "Corning Incorporated" },
  { symbol: "GM", name: "General Motors Company" },
  { symbol: "GOOG", name: "Alphabet Inc. (Google)" },
  { symbol: "GOOGL", name: "Alphabet Inc." },
  { symbol: "GS", name: "The Goldman Sachs Group, Inc." },
  { symbol: "GWW", name: "Grainger (W.W.) Inc." },
  { symbol: "HAL", name: "Halliburton Company" },
  { symbol: "HAS", name: "Hasbro, Inc." },
  { symbol: "HCA", name: "HCA Healthcare, Inc." },
  { symbol: "HD", name: "The Home Depot, Inc." },
  { symbol: "HES", name: "Hess Corporation" },
  { symbol: "HIG", name: "The Hartford Financial Services Group, Inc." },
  { symbol: "HII", name: "Huntington Ingalls Industries, Inc." },
  { symbol: "HOG", name: "Harley-Davidson, Inc." },
  { symbol: "HON", name: "Honeywell International Inc." },
  { symbol: "HPE", name: "Hewlett Packard Enterprise" },
  { symbol: "HPQ", name: "HP Inc." },
  { symbol: "HRL", name: "Hormel Foods Corporation" },
  { symbol: "HSBC", name: "HSBC Holdings plc" },
  { symbol: "HUM", name: "Humana Inc." },
  { symbol: "IBM", name: "International Business Machines Corporation" },
  { symbol: "ICE", name: "Intercontinental Exchange, Inc." },
  { symbol: "IDXX", name: "IDEXX Laboratories, Inc." },
  { symbol: "IEX", name: "IDEX Corporation" },
  { symbol: "IFF", name: "International Flavors & Fragrances Inc." },
  { symbol: "ILMN", name: "Illumina, Inc." },
  { symbol: "INCY", name: "Incyte Corporation" },
  { symbol: "INTC", name: "Intel Corporation" },
  { symbol: "INTU", name: "Intuit Inc." },
  { symbol: "IP", name: "International Paper Company" },
  { symbol: "IPG", name: "Interpublic Group of Companies, Inc." },
  { symbol: "IR", name: "Ingersoll Rand Inc." },
  { symbol: "IRM", name: "Iron Mountain Incorporated" },
  { symbol: "ISRG", name: "Intuitive Surgical, Inc." },
  { symbol: "IT", name: "Gartner, Inc." },
  { symbol: "ITW", name: "Illinois Tool Works Inc." },
  { symbol: "IVZ", name: "Invesco Ltd." },
  { symbol: "J", name: "Jacobs Engineering Group Inc." },
  { symbol: "JCI", name: "Johnson Controls International plc" },
  { symbol: "JPM", name: "JPMorgan Chase & Co." },
  { symbol: "K", name: "Kellogg Company" },
  { symbol: "KEY", name: "KeyCorp" },
  { symbol: "KMI", name: "Kinder Morgan, Inc." },
  { symbol: "KMB", name: "Kimberly-Clark Corporation" },
  { symbol: "KMX", name: "CarMax, Inc." },
  { symbol: "KO", name: "The Coca-Cola Company" },
  { symbol: "KRC", name: "Kilroy Realty Corporation" },
  { symbol: "KSU", name: "Kansas City Southern" },
  { symbol: "L", name: "Loews Corporation" },
  { symbol: "LDOS", name: "Leidos Holdings, Inc." },
  { symbol: "LEG", name: "Leggett & Platt, Inc." },
  { symbol: "LEN", name: "Lennar Corporation" },
  { symbol: "LH", name: "Laboratory Corporation of America Holdings" },
  { symbol: "LMT", name: "Lockheed Martin Corporation" },
  { symbol: "LNC", name: "Lincoln National Corporation" },
  { symbol: "LOW", name: "Lowe's Companies, Inc." },
  { symbol: "LUV", name: "Southwest Airlines Co." },
  { symbol: "LYB", name: "LyondellBasell Industries N.V." },
  { symbol: "MA", name: "Mastercard Incorporated" },
  { symbol: "MAR", name: "Marriott International, Inc." },
  { symbol: "MAS", name: "Masco Corporation" },
  { symbol: "MCD", name: "McDonald's Corporation" },
  { symbol: "MCK", name: "McKesson Corporation" },
  { symbol: "MDT", name: "Medtronic plc" },
  { symbol: "MET", name: "MetLife, Inc." },
  { symbol: "MGM", name: "MGM Resorts International" },
  { symbol: "MKS", name: "MKS Instruments, Inc." },
  { symbol: "MMC", name: "Marsh & McLennan Companies, Inc." },
  { symbol: "MMM", name: "3M Company" },
  { symbol: "MNST", name: "Monster Beverage Corporation" },
  { symbol: "MO", name: "Altria Group, Inc." },
  { symbol: "MON", name: "Monsanto Company" },
  { symbol: "MRO", name: "Marathon Oil Corporation" },
  { symbol: "MS", name: "Morgan Stanley" },
  { symbol: "MSCI", name: "MSCI Inc." },
  { symbol: "MSFT", name: "Microsoft Corporation" },
  { symbol: "MTB", name: "M&T Bank Corporation" },
  { symbol: "MTD", name: "Matthews International Corporation" },
  { symbol: "MU", name: "Micron Technology, Inc." },
  { symbol: "NDAQ", name: "Nasdaq, Inc." },
  { symbol: "NEM", name: "Newmont Corporation" },
  { symbol: "NFLX", name: "Netflix, Inc." },
  { symbol: "NKE", name: "NIKE, Inc." },
  { symbol: "NLOK", name: "NortonLifeLock Inc." },
  { symbol: "NOC", name: "Northrop Grumman Corporation" },
  { symbol: "NOW", name: "ServiceNow, Inc." },
  { symbol: "NRG", name: "NRG Energy, Inc." },
  { symbol: "NSC", name: "Norfolk Southern Corporation" },
  { symbol: "NUE", name: "Nucor Corporation" },
  { symbol: "NVDA", name: "NVIDIA Corporation" },
  { symbol: "NVR", name: "NVR, Inc." },
  { symbol: "NXPI", name: "NXP Semiconductors N.V." },
  { symbol: "O", name: "Realty Income Corporation" },
  { symbol: "ODFL", name: "Old Dominion Freight Line, Inc." },
  { symbol: "OGN", name: "Organon & Co." },
  { symbol: "OKE", name: "OneMain Holdings, Inc." },
  { symbol: "OMC", name: "Omnicom Group Inc." },
  { symbol: "ORCL", name: "Oracle Corporation" },
  { symbol: "OXY", name: "Occidental Petroleum Corporation" },
  { symbol: "PAYX", name: "Paychex, Inc." },
  { symbol: "PCG", name: "PG&E Corporation" },
  { symbol: "PFE", name: "Pfizer Inc." },
  { symbol: "PG", name: "Procter & Gamble Company" },
  { symbol: "PGR", name: "Progressive Corporation" },
  { symbol: "PH", name: "Parker-Hannifin Corporation" },
  { symbol: "PHM", name: "PulteGroup, Inc." },
  { symbol: "PKI", name: "PerkinElmer, Inc." },
  { symbol: "PLD", name: "Prologis, Inc." },
  { symbol: "PM", name: "Philip Morris International Inc." },
  { symbol: "PNC", name: "The PNC Financial Services Group, Inc." },
  { symbol: "PNW", name: "Pinnacle West Capital Corporation" },
  { symbol: "PPL", name: "PPL Corporation" },
  { symbol: "PRGO", name: "Perrigo Company plc" },
  { symbol: "PRU", name: "Prudential Financial, Inc." },
  { symbol: "PSA", name: "Public Storage" },
  { symbol: "PSX", name: "Phillips 66" },
  { symbol: "PXD", name: "Pioneer Natural Resources Company" },
  { symbol: "PYPL", name: "PayPal Holdings, Inc." },
  { symbol: "QCOM", name: "Qualcomm Incorporated" },
  { symbol: "QRVO", name: "Qorvo, Inc." },
  { symbol: "R", name: "Ryder System, Inc." },
  { symbol: "RAI", name: "Reynolds American Inc." },
  { symbol: "RCL", name: "Royal Caribbean Cruises Ltd." },
  { symbol: "RE", name: "Evercore Inc." },
  { symbol: "REGN", name: "Regeneron Pharmaceuticals, Inc." },
  { symbol: "RF", name: "Regions Financial Corporation" },
  { symbol: "RHI", name: "Robert Half International Inc." },
  { symbol: "RJF", name: "Raymond James Financial, Inc." },
  { symbol: "RL", name: "Ralph Lauren Corporation" },
  { symbol: "ROK", name: "Rockwell Automation, Inc." },
  { symbol: "ROP", name: "Roper Technologies, Inc." },
  { symbol: "ROST", name: "Ross Stores, Inc." },
  { symbol: "RSG", name: "Republic Services, Inc." },
  { symbol: "SABR", name: "Sabre Corporation" },
  { symbol: "SBUX", name: "Starbucks Corporation" },
  { symbol: "SCG", name: "SCANA Corporation" },
  { symbol: "SIVB", name: "SVB Financial Group" },
  { symbol: "SKX", name: "Skechers U.S.A., Inc." },
  { symbol: "SLB", name: "Schlumberger Limited" },
  { symbol: "SNA", name: "Snap-On Incorporated" },
  { symbol: "SNPS", name: "Synopsys, Inc." },
  { symbol: "SO", name: "Southern Company" },
  { symbol: "SPG", name: "Simon Property Group, Inc." },
  { symbol: "SPGI", name: "S&P Global Inc." },
  { symbol: "SRE", name: "Sempra Energy" },
  { symbol: "STT", name: "State Street Corporation" },
  { symbol: "STX", name: "Seagate Technology Holdings plc" },
  { symbol: "STZ", name: "Constellation Brands, Inc." },
  { symbol: "SYK", name: "Stryker Corporation" },
  { symbol: "SYMC", name: "Symantec Corporation" },
  { symbol: "T", name: "AT&T Inc." },
  { symbol: "TAP", name: "Molson Coors Beverage Company" },
  { symbol: "TDG", name: "TransDigm Group Incorporated" },
  { symbol: "TE", name: "TE Connectivity Ltd." },
  { symbol: "TEL", name: "TE Connectivity Ltd." },
  { symbol: "TFC", name: "Truist Financial Corporation" },
  { symbol: "TGT", name: "Target Corporation" },
  { symbol: "THC", name: "Tenet Healthcare Corporation" },
  { symbol: "TMO", name: "Thermo Fisher Scientific Inc." },
  { symbol: "TROW", name: "T. Rowe Price Group, Inc." },
  { symbol: "TRV", name: "The Travelers Companies, Inc." },
  { symbol: "TSCO", name: "Tractor Supply Company" },
  { symbol: "TSN", name: "Tyson Foods, Inc." },
  { symbol: "TTWO", name: "Take-Two Interactive Software, Inc." },
  { symbol: "TWTR", name: "Twitter, Inc." },
  { symbol: "TXN", name: "Texas Instruments Incorporated" },
  { symbol: "UAL", name: "United Airlines Holdings, Inc." },
  { symbol: "UDR", name: "UDR, Inc." },
  { symbol: "UHS", name: "Universal Health Services, Inc." },
  { symbol: "ULTA", name: "Ulta Beauty, Inc." },
  { symbol: "UNH", name: "UnitedHealth Group Incorporated" },
  { symbol: "UNP", name: "Union Pacific Corporation" },
  { symbol: "UPS", name: "United Parcel Service, Inc." },
  { symbol: "URI", name: "United Rentals, Inc." },
  { symbol: "USB", name: "U.S. Bancorp" },
  { symbol: "UTX", name: "United Technologies Corporation" },
  { symbol: "V", name: "Visa Inc." },
  { symbol: "VLO", name: "Valero Energy Corporation" },
  { symbol: "VMC", name: "Vulcan Materials Company" },
  { symbol: "VNO", name: "Vornado Realty Trust" },
  { symbol: "VRSN", name: "Verisign, Inc." },
  { symbol: "VRTX", name: "Vertex Pharmaceuticals Incorporated" },
  { symbol: "VZ", name: "Verizon Communications Inc." },
  { symbol: "WDC", name: "Western Digital Corporation" },
  { symbol: "WELL", name: "Welltower Inc." },
  { symbol: "WFC", name: "Wells Fargo & Company" },
  { symbol: "WLTW", name: "Willis Towers Watson plc" },
  { symbol: "WM", name: "Waste Management, Inc." },
  { symbol: "WMT", name: "Walmart Inc." },
  { symbol: "WRB", name: "W.R. Berkley Corporation" },
  { symbol: "WST", name: "West Pharmaceutical Services, Inc." },
  { symbol: "WBA", name: "Walgreens Boots Alliance, Inc." },
  { symbol: "XOM", name: "Exxon Mobil Corporation" },
  { symbol: "XRX", name: "Xerox Holdings Corporation" },
  { symbol: "Xylem", name: "Xylem Inc." },
  { symbol: "YUM", name: "Yum! Brands, Inc." },
  { symbol: "ZBH", name: "Zimmer Biomet Holdings, Inc." },
  { symbol: "ZION", name: "Zions Bancorporation" },
  { symbol: "ZTS", name: "Zoetis Inc." },
];

  
  export default topNYSECompanies;
  